version: '3.8'

networks:
  ai-hub-net:
    driver: bridge

volumes:
  openwebui-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/openwebui
  
  workspace-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/workspace
  
  mcp-configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mcp-configs

services:
  # Open WebUI with persistent storage
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - openwebui-data:/app/backend/data
      - workspace-data:/app/workspace
    environment:
      - DATABASE_URL=sqlite:////app/backend/data/webui.db
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENV=dev
      - ENABLE_API_KEY=true
      - REDIS_URL=${REDIS_URL}
      - DATA_DIR=/app/backend/data
    networks:
      - ai-hub-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Server with Persistent File Operations
  mcp-server:
    build: ./mcp-server
    container_name: mcp-server
    volumes:
      - workspace-data:/app/workspace
      - mcp-configs:/app/configs
    environment:
      - OPENWEBUI_URL=http://open-webui:8080
      - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
      - WORKSPACE_PATH=/app/workspace
      - REDIS_URL=${REDIS_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    networks:
      - ai-hub-net
    restart: unless-stopped
    depends_on:
      - open-webui

  # FileBrowser - Visual File Management
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - workspace-data:/srv
      - /data/filebrowser:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/srv
      - FB_NOAUTH=false
      - FB_USERNAME=${FB_USERNAME}
      - FB_PASSWORD=${FB_PASSWORD}
    networks:
      - ai-hub-net
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/nginx/ssl:/etc/nginx/ssl:ro
      - workspace-data:/var/www/workspace:ro
    networks:
      - ai-hub-net
    depends_on:
      - open-webui
      - mcp-server
      - filebrowser
    restart: unless-stopped
